### ISSUE TITLE
impossible to install with pip

### ISSUE THREAD

**Issue by ricounet67** [usnistgov/etspy#13]
I try to install ETspy with the instructions given but it fails.

I was able to create the etspy environment but when I try to install it with command pip install etspy I have the error message 
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement etspy (from versions: none)
ERROR: No matching distribution found for etspy

When I go to the pypi.org website, etspy can not be found

Do you have any idea of the problem?

**Comment by jat255** [comment]
@ricounet67 sorry for the confusion, we've been working on some changes to the packaging and API for ETSpy in advance of a publication about it, and the packages are not up on PyPI or conda yet. They will be for the 1.0 release, which is expected in the next week or so, hopefully.

**Comment by jat255** [comment]
@ricounet67 You should now be able to install our 1.0 release via pip and/or conda (although may have to wait a couple hours for conda to finish the build). Please reopen this issue if you continue to experience problems, and thanks for your patience!
